version: "3.8"

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres@example/toti-database
    command: npm run dev
    working_dir: /app
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - postgres-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres-volume:
    name: "toti-postgres-volume"
  app-node-modules:
    name: "toti-app-node-modules"